import React, { useState, useEffect } from "react";
import { Box, Text, useStdout } from "ink";
import Spinner from "ink-spinner";
import {
  getRepo,
  getIssuesByLabel,
  commentOnIssue,
  updateIssueBody,
  setIssueLabel,
  type GitHubIssue,
} from "../lib/github.js";
import { createPlan, type PlanResult } from "../lib/claude.js";

type IssueStatus = "pending" | "loading" | "planning" | "commenting" | "done" | "error";

interface IssueState {
  issue: GitHubIssue;
  status: IssueStatus;
  message?: string;
}

interface SeedAppProps {
  repo?: string;
  dryRun?: boolean;
}

export function SeedApp({ repo: repoArg, dryRun }: SeedAppProps) {
  const [repo, setRepo] = useState(repoArg ?? "");
  const [issueStates, setIssueStates] = useState<IssueState[]>([]);
  const [phase, setPhase] = useState<"init" | "fetching" | "planning" | "done">("init");
  const [error, setError] = useState("");
  const [logLines, setLogLines] = useState<string[]>([]);
  const { stdout } = useStdout();

  useEffect(() => {
    run();
  }, []);

  async function run() {
    try {
      let r = repoArg ?? "";
      if (!r) {
        setPhase("init");
        r = await getRepo();
      }
      setRepo(r);

      setPhase("fetching");
      const issues = await getIssuesByLabel(r, "enhancement");

      if (issues.length === 0) {
        setPhase("done");
        return;
      }

      const initial: IssueState[] = issues.map((issue) => ({
        issue,
        status: "pending",
      }));
      setIssueStates(initial);
      setPhase("planning");

      for (let i = 0; i < issues.length; i++) {
        const issue = issues[i];

        setIssueStates((prev) =>
          prev.map((s, idx) => (idx === i ? { ...s, status: "planning" } : s)),
        );

        setLogLines([]);
        let result: PlanResult;
        try {
          result = await createPlan(issue, undefined, (chunk) => {
            setLogLines((prev) => {
              const newLines = (prev.join("") + chunk).split("\n");
              return newLines;
            });
          });
        } catch (err) {
          setIssueStates((prev) =>
            prev.map((s, idx) =>
              idx === i
                ? { ...s, status: "error", message: err instanceof Error ? err.message : "Planning failed" }
                : s,
            ),
          );
          continue;
        }

        if (dryRun) {
          const label = result.type === "questions" ? "questions" : "plan ready";
          setIssueStates((prev) =>
            prev.map((s, idx) =>
              idx === i ? { ...s, status: "done", message: `Dry run — ${label}` } : s,
            ),
          );
          continue;
        }

        // Comment and label
        setIssueStates((prev) =>
          prev.map((s, idx) => (idx === i ? { ...s, status: "commenting" } : s)),
        );

        try {
          if (result.type === "questions") {
            const questionBody =
              "## Questions\n\nBefore implementing this, I have some questions:\n\n" +
              result.questions!.map((q) => `- ${q}`).join("\n") +
              "\n\n---\n*Generated by pr-farmer*";
            await commentOnIssue(r, issue.number, questionBody);
            await setIssueLabel(r, issue.number, "question", "enhancement");
            setIssueStates((prev) =>
              prev.map((s, idx) =>
                idx === i ? { ...s, status: "done", message: "Questions posted" } : s,
              ),
            );
          } else {
            const originalBody = issue.body ? issue.body + "\n\n" : "";
            const planSection =
              "## Implementation Plan\n\n" +
              result.content +
              "\n\n---\n*Generated by pr-farmer — approve by adding the `ready_to_develop` label*";
            await updateIssueBody(r, issue.number, originalBody + planSection);
            await setIssueLabel(r, issue.number, "ready_to_review", "enhancement");
            setIssueStates((prev) =>
              prev.map((s, idx) =>
                idx === i ? { ...s, status: "done", message: "Plan written to issue body" } : s,
              ),
            );
          }
        } catch (err) {
          setIssueStates((prev) =>
            prev.map((s, idx) =>
              idx === i
                ? { ...s, status: "error", message: err instanceof Error ? err.message : "Comment/label failed" }
                : s,
            ),
          );
        }
      }

      setPhase("done");
    } catch (err) {
      setError(err instanceof Error ? err.message : "Unknown error");
      setPhase("done");
    }
  }

  return (
    <Box flexDirection="column" padding={1}>
      <Box marginBottom={1}>
        <Text bold color="cyan">{"🌱 pr-farmer seed"}</Text>
        {repo ? <Text color="gray"> — {repo}</Text> : null}
        {dryRun ? <Text color="yellow"> [dry-run]</Text> : null}
      </Box>

      {phase === "init" && (
        <Box>
          <Text color="yellow"><Spinner type="dots" /></Text>
          <Text> Detecting repository...</Text>
        </Box>
      )}

      {phase === "fetching" && (
        <Box>
          <Text color="yellow"><Spinner type="dots" /></Text>
          <Text> Fetching enhancement issues...</Text>
        </Box>
      )}

      {error ? (
        <Box><Text color="red">Error: {error}</Text></Box>
      ) : null}

      {issueStates.length > 0 && (
        <Box flexDirection="column" marginTop={1}>
          {issueStates.map((s) => (
            <Box key={s.issue.number}>
              <SeedStatusIcon status={s.status} />
              <Text> <Text bold>#{s.issue.number}</Text> {s.issue.title}</Text>
              {s.message && (
                <Text color={s.status === "error" ? "red" : "gray"}> — {s.message}</Text>
              )}
            </Box>
          ))}

          {logLines.length > 0 && phase === "planning" && (
            <LogView lines={logLines} maxRows={Math.max(6, (stdout.rows ?? 24) - issueStates.length - 8)} />
          )}
        </Box>
      )}

      {phase === "done" && !error && (
        <Box marginTop={1}>
          <Text color="green">
            Done! {issueStates.filter((s) => s.status === "done").length} processed,{" "}
            {issueStates.filter((s) => s.status === "error").length} errors.
          </Text>
        </Box>
      )}
    </Box>
  );
}

function SeedStatusIcon({ status }: { status: IssueStatus }) {
  switch (status) {
    case "pending":
      return <Text color="gray">○</Text>;
    case "loading":
      return <Text color="yellow"><Spinner type="dots" /></Text>;
    case "planning":
      return <Text color="cyan"><Spinner type="dots" /></Text>;
    case "commenting":
      return <Text color="blue"><Spinner type="dots" /></Text>;
    case "done":
      return <Text color="green">●</Text>;
    case "error":
      return <Text color="red">✗</Text>;
  }
}

function LogView({ lines, maxRows }: { lines: string[]; maxRows: number }) {
  const visible = lines.slice(-maxRows);
  return (
    <Box flexDirection="column" marginTop={1} height={maxRows}>
      <Box marginBottom={0}>
        <Text color="gray" dimColor>{"─".repeat(40)} claude output {"─".repeat(40)}</Text>
      </Box>
      {visible.map((line, i) => (
        <Text key={i} color="gray" wrap="truncate">{line}</Text>
      ))}
    </Box>
  );
}
